version: '1.0'
stages:
  - clone
  - build
  - test
  - push

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: 'https://github.com/lrochette/CorpSite'
    revision: master
    stage: clone
  build_application:
    title: "Building Globex website"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test
    stage: "test"

  build_image:
    title: "Building tomcat container"
    type: "build"
    image_name: "lrochette/globex"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    disable_push: true
    stage: "build"

  push:
    type: push
    title: "Pushing globex image"
    candidate: ${{build_image}}
    image_name: "lrochette/globex"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    registry: docker-lr
    stage: "push"
