version: '1.0'
stages:
  - clone
  - build
  - test
  - push
  - deploy


steps:

  clone:
    title: Cloning repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    stage: clone

  build_application:
    title: "Building Globex website"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
    stage: "build"

  test:
    title: "Running test"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test
    stage: "test"

  build_image:
    title: "Building tomcat container"
    type: "build"
    image_name: "lrochette/globex"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    disable_push: true
    stage: "build"

  push:
    type: push
    title: "Pushing globex image"
    candidate: ${{build_image}}
    image_name: "lrochette/globex"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    registry: docker-lr
    stage: "push"

  DeployToMyCluster:
    title: deploying to cluster
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster:  cf_onprem_eks
    namespace: demo
    service: globex
    candidate:
      image: lrochette/globex:${{CF_BRANCH_TAG_NORMALIZED}}
      registry: docker-lr
