version: '1.0'
stages:
  - clone
  - build
  - test
  - push
  - deploy


steps:

  clone:
    title: Cloning repository
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    stage: clone

  build_application:
    title: "Building Globex website"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
    stage: "build"

  test:
    title: "Running test"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test
    stage: "test"

  build_image:
    title: "Building tomcat container"
    type: "build"
    image_name: "lrochette/globex"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    disable_push: true
    stage: "build"

  getVersion:
    title: "Get the image version from the repo"
    image: codefresh/cli
    working_directory: "${{clone}}"
    stage: "push"
    commands:
      - |
        export VERSION=$(cat version.txt | tr -d '\n')
        cf_export IMAGE_VERSION=$VERSION
        cf_export IMAGE=lrochette/globex:$VERSION

  push:
    type: push
    title: "Pushing globex image"
    candidate: ${{build_image}}
    image_name: "lrochette/globex"
    tag: ${{IMAGE_VERSION}}
    registry: docker-lr
    stage: "push"


  cloneArgo:
    title: Cloning Gitops repository
    type: git-clone
    git: github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}_gitops
    revision: main
    stage: deploy

  updateVersion:
    title: update the version of the image
    stage: deploy
    image: codefresh/cli
    working_directory: "${{CF_REPO_NAME}}_gitops"
    commands:
      - ls
      - yq -iY '.spec.template.spec.containers[0].image=env.IMAGE' deployment.yaml

  GitCommit:
    title: Commit new image version to Git
    stage: deploy
    type: git-commit
    arguments:
      repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}_gitops
      git: github
      working_directory: "/codefresh/volume/${{CF_REPO_NAME}}_gitops"
      commit_message: "update image to ${{IMAGE_VERSION}}"
      git_user_name: lrochette
      git_user_email: laurent.rochette@codefresh.io
      allow_empty: true
      add:
        - deployment.yaml
