version: '1.0'
stages:
  - clone
  - build
  - test
steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: 'https://github.com/codefresh-io/cli/'
    revision: master
    stage: clone
  build_application:
    title: "Building Globex website"
    type: "freestyle"
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    commands:
      - mvn package
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: maven:3.3-jdk-8
    working_directory: "${{clone}}"
    commands:
      - mvn test
    stage: "test"
    
  build_image:
    title: "Building tomcat container"
    type: "build"
    image_name: "lrochette/globex"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    disable_push: true
    stage: "build"
