apiVersion: v1
kind: Service
metadata:
  labels:
    app: globex
  name: globex
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: globex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: globex
  name: globex
spec:
  selector:
    matchLabels:
      app: globex
  template:
    metadata:
      labels:
        app: globex
    spec:
      containers:
      - name: globex
        image: lrochette/globex
        ports:
        - containerPort: 80
